CREATE TABLE hospedes (
    cpf VARCHAR(11) UNIQUE PRIMARY KEY NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE
);

CREATE TABLE telefones (
    id_telefone INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(15) NOT NULL,
    hospede_cpf VARCHAR(11) NOT NULL,
    FOREIGN KEY (hospede_cpf)
        REFERENCES hospedes (cpf)
);

CREATE TABLE tipos_de_quartos (
    id_tipo_de_quarto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30),
    descricao VARCHAR(70)
);

CREATE TABLE quartos (
    id_quarto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacidade INTEGER,
    valor_diaria DECIMAL(10,2) NOT NULL,
    status VARCHAR(10) NOT NULL,
    tipo_id INTEGER NOT NULL,
    FOREIGN KEY (tipo_id)
        REFERENCES tipos_de_quartos (id_tipo_de_quarto)
);

CREATE TABLE reservas (
    id_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_entrada TIMESTAMP NOT NULL,
    data_saida TIMESTAMP NOT NULL,
    quantidade_hospedes INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    observacao VARCHAR(50),
    hospede_cpf VARCHAR(11) NOT NULL,
    quarto_id INTEGER NOT NULL,
    FOREIGN KEY (hospede_cpf)
        REFERENCES hospedes (cpf),
    FOREIGN KEY (quarto_id)
        REFERENCES quartos (id_quarto)
);

CREATE TABLE servicos (
    id_servico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(20) NOT NULL,
    descricao VARCHAR(50),
    preco DECIMAL(10,2) NOT NULL,
    situacao BOOLEAN NOT NULL
);

CREATE TABLE servicos_reservas (
    id_servico_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_id INTEGER NOT NULL,
    reserva_id INTEGER NOT NULL,
    quantidade_utilizada INTEGER NOT NULL,
    FOREIGN KEY (servico_id)
        REFERENCES servicos (id_servico),
    FOREIGN KEY (reserva_id)
        REFERENCES reservas (id_reserva)
);

CREATE TABLE pagamentos (
    id_pagamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor DECIMAL(10,2) NOT NULL,
    data TIMESTAMP NOT NULL,
    forma_pagamento VARCHAR(10) NOT NULL,
    situacao VARCHAR(20) NOT NULL,
    reserva_id INTEGER NOT NULL,
    FOREIGN KEY (reserva_id)
        REFERENCES reservas (id_reserva)
);